# server {
#     listen 80;
#     server_name ssh.local;
    
#     # proxy_connect 指令必须在 server 块中（不在 location 内）
#     proxy_connect;
#     proxy_connect_allow 443 22 80;
#     proxy_connect_connect_timeout 10s;
#     proxy_connect_read_timeout 10s;
#     proxy_connect_send_timeout 10s;
    
#     location / {
#         proxy_pass http://192.168.1.114:22;
#     }
# }