server {
    listen       80;
    server_name  localhost;

    location /hello {
     echo -n "hello, ";
     echo "world!";
    }

    location /echo {
       echo_before_body hello;
       echo_before_body world;
       proxy_pass $scheme://127.0.0.1:$server_port$request_uri/more;
       echo_after_body hiya;
       echo_after_body igor;
    }
}