# upstream pgsql_backend {
#        server 192.168.1.100:5432;  # 实际 PostgreSQL 服务器
# }

# server {
#    listen 5432;                # 代理监听端口
#    proxy_pass pgsql_backend;
#    proxy_timeout 3s;
#    proxy_connect_timeout 2s;
# }